---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class Agglomeration {<<spatial points>>}
class UWWTP {<<spatial points>>}
class DischargePoint {<<spatial points>>}


classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
