---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR
class DischargePoint {
    + thematicIdIdentifier: wiseIdentifier [1]
    + inspireIdLocalId: string254 [0..1]
    + inspireIdNamespace: string254 [0..1]
    + inspireIdVersionId: string25 [0..1]
    + nameText: string254 [1]
    + nameLanguage: Language [1]
    + nameTextInternational: string254 [0..1]
    + locationStatus: LocationStatus [1]
    + latitude: NumberDecimalType [0..1]
    + longitude: NumberDecimalType [0..1]
    + conditionOfFacility: ConditionOfFacility [1]
    + receivingType: ReceivingType [1]
    + waterBodyCode: wiseIdentifier [0..1]
    + wiseEvolutionType: WiseEvolutionType [1]
    + supersedesIdentifier: wiseIdentifier [0..n]
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
