---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class Derogation{
    + article3_2DeadlineExtension: DeadlineExtension_Enum [1]
    + article3_2CompleteCollectingSystem: nonNegativeValue [0..1]
    + article3_2NonCompleteCollectingSystem: nonNegativeValue [0..1]
    + article3_2CompleteCollectingSystemLoad: nonNegativeValue [0..1]
    + article3_2NonCompleteCollectingSystemLoad: nonNegativeValue [0..1]
    + article3_2InvestmentPlanReference: referenceCode [0..1]
    + article3_2ExtensionReasonReference: referenceCode [0..1]

    + article3_2CulturalHeritage: YesNo [1]
    + article3_2CulturalHeritageReference: referenceCode [0..1]
    + article6_3CulturalHeritage: YesNo [1]
    + article6_3CulturalHeritageReference: referenceCode [0..1]

    + article6_3DeadlineExtension: DeadlineExtension_Enum [1]
    + article6_3AgglomerationsWithSecondaryTreatment: nonNegativeValue [0..1]
    + article6_3AgglomerationsWithoutSecondaryTreatment: nonNegativeValue [0..1]
    + article6_3LoadWithSecondaryTreatment: nonNegativeValue [0..1]
    + article6_3LoadWithoutSecondaryTreatment: nonNegativeValue [0..1]
    + article6_3InvestmentPlanReference: referenceCode [0..1]
    + article6_3ExtensionReasonReference: referenceCode [0..1]

    + article6_4LessStringentTreatment: YesNo [1]
    + article6_4LessStringentStudyReference: referenceCode [0..1]

    + article7_4DeadlineExtension: DeadlineExtensionArticle7_4_Enum [1]
    + article7_4AgglomerationsWithTertiaryTreatment: nonNegativeValue [0..1]
    + article7_4AgglomerationsWithoutTertiaryTreatment: nonNegativeValue [0..1]
    + article7_4InvestmentPlanReference: referenceCode [0..1]
    + article7_4ExtensionReasonReference: referenceCode [0..1]
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
