---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class Agglomeration{
    + code: wiseIdentifier [1]
    + name: string255 [1]
    + status: Status_Enum [1]
    + measures: AgglomerationMeasure_Enum [1]
    + prioritisation: Priority_Enum [1]

    + completionDate: date [1]
    + expectedLoad: nonNegativeValue [1]
    + expectedLoadCollected: Percentage [0..1]
    + expectedLoadIndividualSystems: Percentage [0..1]

    + investment: nonNegativeValue [1]
    + europeanUnionFund: nonNegativeValue [1]
    + europeanUnionFundName: EUFund_Enum [0..1]
    + otherPublicFund: nonNegativeValue [1]
    + otherPublicFundSpecification: OtherPublicFund_Enum [0..1]
    + loan: nonNegativeValue [1]
    + loanName: string255 [0..1]
    + remarks: string1000 [0..1]
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
