---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class Contact{
<<private>>
    + name: string100 [1]
    + institution: string255 [1]
    + phone: string100 [1]
    + email: Email [1]
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
