---
config:
  class:
    hideEmptyMembersBox: true
  layout: dagre
  theme: neutral
---
classDiagram
direction LR

class MSSummary{
    + situationAt: date [1]
    + programmeObligation: YesNo [1]
    + programmeReference: referenceCode [0..1]
    + prioritisationReference: referenceCode [0..1]

    + article3Compliance: ComplianceSelfAssessment_Enum [1]
    + article4Compliance: ComplianceSelfAssessment_Enum [1]
    + article5Compliance: ComplianceSelfAssessment_Enum [1]
    + article5ManagementPlanReference: referenceCode [0..1]
    + article6Compliance: ComplianceSelfAssessment_Enum [1]
    + article7Compliance: ComplianceSelfAssessment_Enum [1]
    + article8Compliance: ComplianceSelfAssessment_Enum [1]

    + riskAssessment: YesNo [1]
    + riskDate: date [0..1]
    + riskIdentified: YesNo [0..1]
    + riskSummaryReference: referenceCode [0..1]

    + producerResponsibilityContribution: nonNegativeValue [1]
    + producerResponsibilityEstimateBasedOn: EstimateBasis_Enum [1]
    + sufficientResources2033: YesNo [1]
    + sufficientResources2036: YesNo [1]
    + sufficientResources2039: YesNo [1]
    + sufficientResources2045: YesNo [1]
    + otherPeriod: string255 [0..1]
    + remarks: string1000 [0..1]
}

classDef default fill:white,stroke:#000;
classDef forFixing fill:white,stroke:#f00;
